from __future__ import annotations

from sqlalchemy import (
    Boolean,
    Column,
    ForeignKey,
    Integer,
    MetaData,
    Numeric,
    Table,
    Text,
    UniqueConstraint,
    text,
)

metadata = MetaData()


def uuid_column(name: str, *, primary_key: bool = False, nullable: bool = True) -> Column[str]:
    return Column(name, Text, primary_key=primary_key, nullable=nullable)


def timestamp_column(name: str, *, nullable: bool = True) -> Column[str]:
    return Column(name, Text, nullable=nullable)


def json_column(name: str, *, nullable: bool = True) -> Column[str]:
    return Column(name, Text, nullable=nullable)


trader_raw_messages = Table(
    "trader_raw_messages",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("source", Text, nullable=False),
    Column("source_url", Text),
    Column("author", Text),
    timestamp_column("timestamp", nullable=False),
    Column("raw_text", Text, nullable=False),
    json_column("attachments"),
    uuid_column("reply_to"),
    timestamp_column("imported_at"),
    Column("content_hash", Text),
    UniqueConstraint("content_hash"),
)

trader_semantic_events = Table(
    "trader_semantic_events",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("raw_message_id", Text, ForeignKey("trader_raw_messages.id")),
    timestamp_column("timestamp", nullable=False),
    Column("symbol", Text),
    json_column("aliases"),
    Column("asset_class", Text),
    Column("action", Text),
    Column("direction", Text),
    Column("timeframe", Text),
    Column("instrument", Text),
    Column("setup_hint", Text),
    Column("entry_condition", Text),
    Column("invalidation", Text),
    Column("target", Text),
    Column("stop", Text),
    Column("thesis", Text),
    json_column("catalyst"),
    json_column("risk_notes"),
    Column("language_strength", Text),
    Column("confidence", Numeric),
    Column("extractor_version", Text),
    timestamp_column("created_at"),
    UniqueConstraint("raw_message_id", "setup_hint", "extractor_version"),
)

market_context_snapshots = Table(
    "market_context_snapshots",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("event_id", Text, ForeignKey("trader_semantic_events.id")),
    timestamp_column("timestamp", nullable=False),
    Column("symbol", Text, nullable=False),
    Column("symbol_price", Numeric),
    Column("symbol_vwap", Numeric),
    Column("symbol_above_vwap", Boolean),
    Column("symbol_relative_strength_vs_qqq", Numeric),
    Column("symbol_relative_volume", Numeric),
    json_column("spy_state"),
    json_column("qqq_state"),
    json_column("vix_state"),
    json_column("btc_state"),
    json_column("eth_state"),
    json_column("news_summary"),
    json_column("options_summary"),
    Column("context_builder_version", Text),
    timestamp_column("created_at"),
    UniqueConstraint("event_id", "context_builder_version"),
)

event_outcomes = Table(
    "event_outcomes",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("event_id", Text, ForeignKey("trader_semantic_events.id")),
    Column("symbol", Text, nullable=False),
    Column("return_30m", Numeric),
    Column("return_1h", Numeric),
    Column("return_eod", Numeric),
    Column("return_1d", Numeric),
    Column("return_3d", Numeric),
    Column("return_5d", Numeric),
    Column("return_10d", Numeric),
    Column("mfe", Numeric),
    Column("mae", Numeric),
    Column("outperformed_qqq", Boolean),
    Column("hit_stop", Boolean),
    Column("hit_target", Boolean),
    Column("final_label", Text),
    Column("notes", Text),
    timestamp_column("calculated_at"),
    UniqueConstraint("event_id"),
)

playbooks = Table(
    "playbooks",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("name", Text, nullable=False),
    Column("description", Text),
    json_column("symbols"),
    Column("setup_type", Text),
    json_column("required_market_regime"),
    json_column("required_conditions"),
    json_column("invalidation_conditions"),
    Column("preferred_timeframe", Text),
    json_column("preferred_instrument"),
    Column("historical_win_rate", Numeric),
    Column("avg_return", Numeric),
    Column("avg_mfe", Numeric),
    Column("avg_mae", Numeric),
    Column("sample_size", Integer),
    Column("confidence", Numeric),
    Column("version", Text),
    Column("status", Text),
    timestamp_column("created_at"),
    timestamp_column("updated_at"),
    UniqueConstraint("setup_type", "version"),
)

signals = Table(
    "signals",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    timestamp_column("created_at"),
    timestamp_column("updated_at"),
    Column("symbol", Text, nullable=False),
    Column("timeframe", Text, nullable=False),
    Column("setup_type", Text, nullable=False),
    Column("score", Numeric),
    Column("status", Text),
    Column("market_gate", Text),
    Column("trader_playbook_match", Numeric),
    Column("entry_trigger", Text),
    Column("invalidation", Text),
    Column("preferred_instrument", Text),
    json_column("evidence"),
    json_column("risk_flags"),
    json_column("tool_outputs"),
    Column("rule_version", Text),
    Column("agent_version", Text),
)

trade_tickets = Table(
    "trade_tickets",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("signal_id", Text, ForeignKey("signals.id")),
    Column("symbol", Text, nullable=False),
    Column("direction", Text, nullable=False),
    Column("instrument", Text, nullable=False),
    Column("timeframe", Text, nullable=False),
    Column("entry_plan", Text),
    Column("stop_plan", Text),
    Column("target_1", Text),
    Column("target_2", Text),
    Column("max_loss_nav_pct", Numeric),
    Column("position_size_rule", Text),
    Column("status", Text),
    json_column("rationale"),
    json_column("invalidation"),
    timestamp_column("created_at"),
    timestamp_column("approved_at"),
    timestamp_column("rejected_at"),
)

agent_messages = Table(
    "agent_messages",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    timestamp_column("created_at"),
    Column("priority", Text, nullable=False),
    Column("type", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("body", Text, nullable=False),
    json_column("scope"),
    json_column("evidence"),
    json_column("risk_flags"),
    json_column("actions"),
    Column("requires_ack", Boolean, server_default=text("0")),
    timestamp_column("acknowledged_at"),
    timestamp_column("dismissed_at"),
)

agent_events = Table(
    "agent_events",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    timestamp_column("timestamp"),
    uuid_column("run_id"),
    uuid_column("task_id"),
    uuid_column("signal_id"),
    Column("symbol", Text),
    Column("event_type", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("title", Text),
    Column("summary", Text),
    json_column("input_summary"),
    json_column("output_summary"),
    Column("tool_name", Text),
    Column("duration_ms", Integer),
    Column("error", Text),
)

agent_tasks = Table(
    "agent_tasks",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    timestamp_column("created_at"),
    timestamp_column("updated_at"),
    Column("name", Text, nullable=False),
    Column("description", Text),
    Column("task_type", Text, nullable=False),
    json_column("scope"),
    json_column("schedule"),
    json_column("triggers"),
    json_column("allowed_tools"),
    json_column("approval_policy"),
    Column("status", Text, nullable=False),
)

agent_rules = Table(
    "agent_rules",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    timestamp_column("created_at"),
    timestamp_column("updated_at"),
    Column("name", Text, nullable=False),
    Column("description", Text),
    Column("rule_type", Text, nullable=False),
    json_column("scope"),
    json_column("condition"),
    json_column("action"),
    Column("priority", Integer, server_default=text("0")),
    Column("status", Text, nullable=False),
    Column("version", Text, nullable=False),
)

agent_capabilities = Table(
    "agent_capabilities",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("name", Text, nullable=False),
    Column("description", Text),
    Column("category", Text, nullable=False),
    Column("tool_name", Text, nullable=False),
    Column("permission_level", Text, nullable=False),
    json_column("rate_limit"),
    json_column("cost_policy"),
    json_column("allowed_tasks"),
    json_column("blocked_tasks"),
    Column("status", Text, nullable=False),
    timestamp_column("updated_at"),
)

approval_requests = Table(
    "approval_requests",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    timestamp_column("created_at"),
    Column("request_type", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("description", Text),
    Column("requested_by", Text, nullable=False),
    json_column("payload"),
    json_column("risk_summary"),
    json_column("evidence"),
    Column("status", Text, nullable=False),
    timestamp_column("expires_at"),
    Column("decided_by", Text),
    timestamp_column("decided_at"),
    Column("decision_note", Text),
)

human_feedback = Table(
    "human_feedback",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("object_type", Text, nullable=False),
    uuid_column("object_id", nullable=False),
    Column("feedback_type", Text, nullable=False),
    json_column("correction"),
    Column("notes", Text),
    timestamp_column("created_at"),
)

rule_candidates = Table(
    "rule_candidates",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    timestamp_column("created_at"),
    timestamp_column("updated_at"),
    Column("source", Text, nullable=False),
    json_column("source_ref"),
    Column("hypothesis", Text, nullable=False),
    json_column("symbols", nullable=False),
    Column("trigger_definition", Text, nullable=False),
    Column("entry_condition", Text, nullable=False),
    Column("exit_condition", Text),
    Column("invalidation", Text, nullable=False),
    json_column("data_requirements", nullable=False),
    json_column("risk_notes"),
    Column("status", Text, nullable=False),
    Column("confidence", Numeric),
    Column("created_by", Text, nullable=False),
    uuid_column("latest_report_id"),
    uuid_column("approval_request_id"),
    uuid_column("versioned_rule_id"),
)

rule_candidate_evidence_requirements = Table(
    "rule_candidate_evidence_requirements",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("candidate_id", Text, ForeignKey("rule_candidates.id")),
    timestamp_column("created_at"),
    Column("requirement_type", Text, nullable=False),
    Column("provider_capability", Text, nullable=False),
    json_column("query_scope", nullable=False),
    json_column("required_quality"),
    Column("status", Text, nullable=False),
    json_column("evidence_refs"),
    Column("gap_reason", Text),
)

lite_backtest_reports = Table(
    "lite_backtest_reports",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("candidate_id", Text, ForeignKey("rule_candidates.id")),
    timestamp_column("created_at"),
    timestamp_column("data_window_start", nullable=False),
    timestamp_column("data_window_end", nullable=False),
    Column("sample_size", Integer, nullable=False),
    json_column("trigger_logic", nullable=False),
    json_column("entry_logic", nullable=False),
    json_column("exit_logic"),
    json_column("invalidation_logic", nullable=False),
    Column("win_rate", Numeric),
    Column("avg_return", Numeric),
    Column("median_return", Numeric),
    Column("max_adverse_excursion", Numeric),
    Column("max_favorable_excursion", Numeric),
    json_column("cost_model", nullable=False),
    Column("spread_assumption", Text),
    Column("slippage_assumption", Text),
    json_column("evidence_gaps"),
    json_column("quality_flags"),
    Column("decision", Text, nullable=False),
    Column("reason", Text, nullable=False),
    Column("next_review_trigger", Text),
)

rule_proposals = Table(
    "rule_proposals",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("candidate_id", Text, ForeignKey("rule_candidates.id")),
    Column("report_id", Text, ForeignKey("lite_backtest_reports.id")),
    timestamp_column("created_at"),
    timestamp_column("updated_at"),
    Column("title", Text, nullable=False),
    json_column("proposed_rule", nullable=False),
    json_column("evidence_summary", nullable=False),
    json_column("risk_summary", nullable=False),
    Column("status", Text, nullable=False),
    uuid_column("approval_request_id"),
    uuid_column("version_id"),
)

rule_versions = Table(
    "rule_versions",
    metadata,
    uuid_column("id", primary_key=True, nullable=False),
    Column("proposal_id", Text, ForeignKey("rule_proposals.id")),
    timestamp_column("created_at"),
    Column("version", Text, nullable=False),
    json_column("rulepack_patch", nullable=False),
    Column("migration_note", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("approved_by", Text),
    timestamp_column("approved_at"),
    timestamp_column("activated_at"),
)
